default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

primary: &primary
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>

secondary:
  <<: *default
  url: <%= ENV['FACET_V1_VM_DATABASE_URL'] %>

development:
  primary:
    <<: *primary

test:
  primary:
    <<: *primary

production:
  primary:
    <<: *primary
