default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username:
  password:

development:
  <<: *default
  database: evm_facet_development

test:
  <<: *default
  database: evm_facet_test

production:
  <<: *default
  database: evm_facet_production

secondary:
  <<: *default
  url: <%= ENV['SECONDARY_DB_URL'] %>
