default: &default
  adapter: "<%= ENV['MIGRATION_MODE'] == 'true' ? 'postgresql' : 'sqlite3' %>"
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

primary: &primary
  <<: *default
  url: "<%= ENV['MIGRATION_MODE'] == 'true' ? ENV.fetch('DATABASE_URL') : 'sqlite3::memory:' %>"

secondary:
  <<: *default
  url: <%= ENV['FACET_V1_VM_DATABASE_URL'] %>

development:
  primary:
    <<: *primary

test:
  primary:
    <<: *primary

production:
  primary:
    <<: *primary
