[profile.default]
src = "src"
out = 'forge-artifacts'
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
# solc_version = "0.8.24"


remappings = [
    "solady/=lib/solady/",
    "src/=src/",
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts'
]
