name: Build Sequencer Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag (default: branch name)'
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine tag
        id: tag
        run: |
          if [[ -n "${{ inputs.tag }}" ]]; then
            echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          else
            # Use branch name as tag, replace / with -
            BRANCH=${GITHUB_REF#refs/heads/}
            echo "tag=${BRANCH//\//-}" >> $GITHUB_OUTPUT
          fi

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/0xfacet/facet-sequencer
          tags: |
            type=raw,value=${{ steps.tag.outputs.tag }}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./sequencer
          file: ./sequencer/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/0xfacet/facet-sequencer:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/0xfacet/facet-sequencer:buildcache,mode=max